# Generated by Django 3.2.4 on 2021-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210615_1032'),
    ]


